### PR TITLE
Remove need for separate asset script

### PR DESCRIPTION
**Pull request by jonahwilliams**
Moves framework sync and local engine flags into tool in https://github.com/flutter/flutter/pull/31515

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Not sure if I should remove this for testbed as well...

**Comment by stuartmorgan** [comment]
> Not sure if I should remove this for testbed as well...

I was going to do some cleanup on testbed/ today, and as part of that I'll evaluate how to handle the transition in a way that won't make the local development workflow overly complex in the short term. (The current setup evolved precisely to avoid the problem of having to change several things in several places to get local development working, so I want to avoid having things split too much as the tooling is evolving.)

**Comment by stuartmorgan** [comment]
Looking again at the way engine override is plumbed: with this change we should be able to switch testbed over to using the same flow as example/, since the script handles both `build bundle` and the asset copying, which is all the the old flow was managing. \o/

**Comment by stuartmorgan** [comment]
`testbed` is broken because it was still using `build_flutter_assets` instead of calling the `flutter_tools` script (since that didn't used to have local engine support). You'll need to update that script step to match the earlier `example` change to use the shared script.

**Pull request merged**
