### PR TITLE
Initial Linux GN build

### PR DESCRIPTION
**Pull request by stuartmorgan**
Adds an experimental GN-based build as an alternative to the Make-based
build on Linux.

The example application does not use GN for its own build since it is
intended to serve as an example of using the embedding library, so it
continues to use the more common Make as clients are unlikely to be
using GN.

First step toward possible approach to #114

### CODE REVIEW

**Comment by krisgiesing** [comment]
Sorry I haven't had time to take a look at this. I may not be the best reviewer anyway since I don't know a lot about GN. I'll try to find a reviewer with more knowledge.

**Comment by stuartmorgan** [comment]
FWIW, I'm fine a reviewer that's not a GN expert; I can always look for an expert GN review later if this does turn out to be a viable replacement for the builds across all three platforms.

**Comment by krisgiesing** [comment]
RSLGTM. Just so I understand, the intent here is for those building the library to use GN, but those consuming the library may use other systems (e.g. Make on Linux, Xcode on Mac)? So we are looking ahead to a system where we might publish prebuilt libraries to clients rather than having them build from source?

**Comment by stuartmorgan** [comment]
> So we are looking ahead to a system where we might publish prebuilt libraries to clients rather than having them build from source?

Exactly. Since that's the model used by Flutter, it seems like the natural direction for this project to go in longer term so that the workflows match the expectations of existing Flutter developers.

**Comment by krisgiesing** [comment]
> Exactly. Since that's the model used by Flutter, it seems like the natural direction for this project to go in longer term so that the workflows match the expectations of existing Flutter developers.

Sounds good to me. Thanks for clarifying!

**Pull request merged**
