### PR TITLE
Add User Specific Files For Debugging

### PR DESCRIPTION
**Pull request by CallumIddon**
This will include the debugging configuration required for VS to correctly run the embedder from inside VS. This includes the configuration that the working directory needs to be the solution directory not the project directory.

### CODE REVIEW

**Comment by stuartmorgan** [comment]
I don't have access to my Windows machine at the moment to test; does
https://stackoverflow.com/questions/38295289/how-to-store-visual-studios-debug-configuration-in-source-control
still work in VS 2017 so that we wouldn't need to check in the user-specific file?

**Comment by CallumIddon** [comment]
Works for me if you could test it just in case that would be great.

**Comment by b-strauss** [comment]
Works great on my machine with Visual Studio Community!

**Comment by gedw99** [comment]
Ah that's great to hear :)

**Comment by gedw99** [comment]
I presume by VS you don't mean VS Code ? Just checking

**Comment by CallumIddon** [comment]
@stuartmorgan should be good to land. And yes this is Visual Studio not Visual Studio Code.

**Comment by stuartmorgan** [comment]
Great, will land now since it's confirmed working (I wasn't going to be able to test until Monday).

**Pull request merged**
