### PR TITLE
Custom Cursor Plugin

### PR DESCRIPTION
**Pull request by rodydavis**
Lets you set a custom cursor on desktop at runtime

- MacOS
- Windows
- Linux (in Progress)

On Windows you need to modify you win32_window.cc

```
LRESULT
Win32Window::MessageHandler(HWND hwnd, UINT const message, WPARAM const wparam,
                            LPARAM const lparam) noexcept
{
  auto window =
      reinterpret_cast<Win32Window *>(GetWindowLongPtr(hwnd, GWLP_USERDATA));

  if (window == nullptr)
  {
    return 0;
  }

  switch (message)
  {
  case WM_SETCURSOR:
    return TRUE;
```

Add this to the top of the switch statement:

```
 case WM_SETCURSOR:
    return TRUE;
```

### CODE REVIEW

**Comment by rodydavis** [comment]
Depends on https://github.com/google/flutter-desktop-embedding/pull/637

**Comment by rodydavis** [comment]
This will update the cursor on windows and Mac

**Comment by dkwingsmt** [comment]
Hello @rodydavis. Thanks for the giant PR! I only took a brief look at the code for now, so let me know if I misunderstood anything.

Since you've also found my PR (it hasn't been updated for a while but I am still on it), you probably saw that I took a different approach. The biggest difference is to do it declaratively, i.e. instead of 
```dart
  MouseRegion(
    onEnter: (_) { myCursor.setCursor() },
    onExit: (_) { myCursor.resetCursor() },
  )
```
It goes
```dart
  MouseRegion(
    cursor: myCursor,
  )
```
The benefit of declarative programming is that it goes with the other parts of Flutter, and lower the possibility of errors by reducing boilerplate. The Flutter framework prefers "level-sensitive" to "edge-sensitive". It also provides a natural "stack" since it uses the existing layer tree.

Additionally, there are more objectives that I'd really like to achieve with this mouse cursor API. Most notably,
- Besides desktop platforms, it should also support Android and Web.
- It should also support creating cursors from images.
- In order to [avoid the lowest common denominator], it should support as many cursor types (as well as other features) as possible, even if the cursor is only supported on one platform. 

I'm glad to discuss in more details if you'd like to, so please let me know your opinions. :)

**Comment by rodydavis** [comment]
If you look at my code I do support all specific desktop cursors as well as the shared ones:

```dart

enum CursorType {
  arrow,
  cross,
  hand,
  resizeLeft,
  resizeRight,
  resizeDown,
  resizeUp,
  resizeLeftRight,
  resizeUpDown,
}

enum MacOSCursorType {
  arrow,
  beamVertical,
  crossHair,
  closedHand,
  openHand,
  pointingHand,
  resizeLeft,
  resizeRight,
  resizeDown,
  resizeUp,
  resizeLeftRight,
  resizeUpDown,
  beamHorizontial,
  disappearingItem,
  notAllowed,
  dragLink,
  dragCopy,
  contextMenu,
}

enum WindowsCursorType {
  appStart,
  arrow,
  cross,
  hand,
  help,
  iBeam,
  no,
  resizeAll,
  resizeNESW,
  resizeNS,
  resizeNWSE,
  resizeWE,
  upArrow,
  wait,
}

enum LinuxCursorType {
  arrow,
  iBeam,
  crossHair,
  hand,
  horizontalResize,
  verticalResize,
}

```

As for your approach I love the simplicity, but both options need to be available. As in some situations you can set the cursor to loading or disabled if something on the backend triggers it. 

I think there should be two layers. Declarative and Region API. That way we get the benefit of both! In this case I am working on the backend triggering the events.

**Comment by rodydavis** [comment]
I can check for the correct cursor too even if no specific ones are defines:

```dart
static String _getCursor(CursorType cursor, MacOSCursorType macOS,
      WindowsCursorType windows, LinuxCursorType linux) {
    if (Platform.isMacOS) {
      if (macOS == null) {
        switch (cursor) {
          case CursorType.arrow:
            macOS = MacOSCursorType.arrow;
            break;
          case CursorType.cross:
            macOS = MacOSCursorType.crossHair;
            break;
          case CursorType.hand:
            macOS = MacOSCursorType.openHand;
            break;
          case CursorType.resizeLeft:
            macOS = MacOSCursorType.resizeLeft;
            break;
          case CursorType.resizeRight:
            macOS = MacOSCursorType.resizeRight;
            break;
          case CursorType.resizeDown:
            macOS = MacOSCursorType.resizeDown;
            break;
          case CursorType.resizeUp:
            macOS = MacOSCursorType.resizeUp;
            break;
          case CursorType.resizeLeftRight:
            macOS = MacOSCursorType.resizeLeftRight;
            break;
          case CursorType.resizeUpDown:
            macOS = MacOSCursorType.resizeUpDown;
            break;
        }
      }
      return describeEnum(macOS);
    }
    if (Platform.isWindows) {
      if (windows == null) {
        switch (cursor) {
          case CursorType.arrow:
            windows = WindowsCursorType.arrow;
            break;
          case CursorType.cross:
            windows = WindowsCursorType.cross;
            break;
          case CursorType.hand:
            windows = WindowsCursorType.hand;
            break;
          case CursorType.resizeLeftRight:
          case CursorType.resizeLeft:
          case CursorType.resizeRight:
            windows = WindowsCursorType.resizeWE;
            break;
          case CursorType.resizeUpDown:
          case CursorType.resizeDown:
          case CursorType.resizeUp:
            windows = WindowsCursorType.resizeNS;
            break;
        }
      }
      return describeEnum(windows);
    }
    if (Platform.isLinux) {
      if (linux == null) {
        switch (cursor) {
          case CursorType.arrow:
            linux = LinuxCursorType.arrow;
            break;
          case CursorType.cross:
            linux = LinuxCursorType.crossHair;
            break;
          case CursorType.hand:
            linux = LinuxCursorType.hand;
            break;
          case CursorType.resizeLeftRight:
          case CursorType.resizeLeft:
          case CursorType.resizeRight:
            linux = LinuxCursorType.horizontalResize;
            break;
          case CursorType.resizeUpDown:
          case CursorType.resizeDown:
          case CursorType.resizeUp:
            linux = LinuxCursorType.verticalResize;
            break;
        }
      }
      return describeEnum(linux);
    }
    return "none";
  }
}
```

**Comment by rodydavis** [comment]
You are welcome! Glad I can help contribute.

**Comment by rodydavis** [comment]
@dkwingsmt I also made a PR for Flutter. I even added Web support for Flutter Web and it works really well and has even more cursors: 

https://github.com/flutter/plugins/pull/2462

**Comment by stuartmorgan** [comment]
FYI I'm holding off on reviewing this for now since there are significant open questions about the Windows side (and there's code in here that isn't ready for review as well; the Linux code is just the template, and there's a bunch of Android and iOS cruft).

**Comment by rodydavis** [comment]
Sounds great! 👍🏼

**Comment by stuartmorgan** [comment]
Since the framework support for cursors is well underway, and it's likely that will be done before I have time to revisit the Windows plugin API to make this possible to support correctly on Windows as a plugin, I'm going to close this PR; it no longer makes sense to prototype this here given the progress in the framework.

**Comment by rodydavis** [comment]
Sounds great!

**Pull request closed without merging**
